### ISSUE TITLE
Git Error: failed to find branch `master`

### ISSUE THREAD

**Issue by HadarHindy** [jazcarate/cloudflare-worker-google-oauth#1]
Hey,
I'm trying to use this repo and when I try to use: wrangler generate [a name] https://github.com/jazcarate/cloudflare-worker-google-oauth I'm encountering this problem: Git Error: failed to find branch `master`.
Would love for some help!
Thanks in advance :)

**Comment by jazcarate** [comment]
Hello @HadarHindy ! Thank you for pointing this out. At some point I made the default branch `main` rather than `master` ([see why here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)) and I didn't test the generate.

I see that there is a pending PR on `wrangler` itself to allow a branch name as an argument (https://github.com/cloudflare/wrangler/pull/1653) but until it is merged, I've move the default branch back to `master`.

Thank you for pointing this out!
